name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ejecutar
      id: ejecutar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ejecutar
        setup-command: gcc main.c -o main
        command: "./main"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EJECUTAR_RESULTS: "${{steps.ejecutar.outputs.result}}"
      with:
        runners: ejecutar
